const sequelize = require('./config/database');

async function fix() {
    try {
        const [results] = await sequelize.query("SHOW INDEX FROM nguoidung;");
        console.log(`Total indexes on nguoidung: ${results.length}`);
        let dropped = 0;

        for (const index of results) {
            const keyName = index.Key_name;
            // Drop duplicate Email indexes generated by Sequelize alter sync
            // Typically named Email, Email_2, Email_3...
            // or Email_uk, Email_unique...
            if (keyName !== 'PRIMARY' && (keyName.startsWith('Email') || keyName.match(/_[0-9]+$/))) {
                try {
                    await sequelize.query(`ALTER TABLE nguoidung DROP INDEX \`${keyName}\`;`);
                    console.log(`Dropped index: ${keyName}`);
                    dropped++;
                } catch (e) {
                    console.log(`Could not drop ${keyName}: ${e.message}`);
                }
            }
        }
        console.log(`Total dropped: ${dropped}`);
        process.exit(0);
    } catch (error) {
        console.error(error);
        process.exit(1);
    }
}
fix();
